development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sailcore_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sailcore_production
  # Uncomment this if using Heroku
  # redis_url: <%= ENV['REDIS_URL'] %>
